export const data = [
  {
    _id: 1,
    name: 'Test1',
    type: 'income',
    category: undefined,
    value: '20,49',
    createdAt: new Date(),
  },
  {
    _id: 1,
    name: 'Test2',
    type: 'expense',
    category: 'personal',
    value: '15,99',
    createdAt: new Date(),
  },
  {
    _id: 1,
    name: 'Test3',
    type: 'income',
    category: undefined,
    value: '15,99',
    createdAt: new Date(),
  },
  {
    _id: 1,
    name: 'Test4',
    type: 'income',
    category: undefined,
    value: '15,99',
    createdAt: new Date(),
  },
  {
    _id: 1,
    name: 'Test5',
    type: 'expense',
    category: 'transport',
    value: '35,99',
    createdAt: new Date(),
  },
  {
    _id: 1,
    name: 'Test6',
    type: 'income',
    category: undefined,
    value: '15,99',
    createdAt: new Date(),
  },
  {
    _id: 1,
    name: 'Test7',
    type: 'expense',
    category: 'health',
    value: '59,99',
    createdAt: new Date(),
  },
  {
    _id: 1,
    name: 'Test8',
    type: 'income',
    category: undefined,
    value: '15,99',
    createdAt: new Date(),
  },
  {
    _id: 1,
    name: 'Test9',
    type: 'expense',
    category: 'other',
    value: '145,99',
    createdAt: new Date(),
  },
  {
    _id: 1,
    name: 'Test10',
    type: 'income',
    category: undefined,
    value: '15,99',
    createdAt: new Date(),
  },
  {
    _id: 1,
    name: 'Test11',
    type: 'income',
    category: undefined,
    value: '15,99',
    createdAt: new Date(),
  },
  {
    _id: 1,
    name: 'Test12',
    type: 'expense',
    category: 'food',
    value: '150,21',
    createdAt: new Date(),
  },
  {
    _id: 1,
    name: 'Test13',
    type: 'income',
    category: 'transport',
    value: '5,99',
    createdAt: new Date(),
  },
  {
    _id: 1,
    name: 'Test14',
    type: 'income',
    category: undefined,
    value: '15,99',
    createdAt: new Date(),
  },
  {
    _id: 1,
    name: 'Test15',
    type: 'expense',
    category: 'personal',
    value: '10,99',
    createdAt: new Date(),
  },
  {
    _id: 1,
    name: 'Test16',
    type: 'income',
    category: 'food',
    value: '5,99',
    createdAt: new Date(),
  },
  {
    _id: 1,
    name: 'Test17',
    type: 'expense',
    category: 'food',
    value: '12,99',
    createdAt: new Date(),
  },
  {
    _id: 1,
    name: 'Test18',
    type: 'expense',
    category: 'personal',
    value: '12,99',
    createdAt: new Date(),
  },
  {
    _id: 1,
    name: 'Test19',
    type: 'expense',
    category: 'health',
    value: '23,99',
    createdAt: new Date(),
  },
];
